/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/twilio/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Twilio Voice webhook
         * @description Primary Twilio Voice webhook endpoint. Handles inbound calls and status callbacks.
         *     Responds with TwiML.
         *
         *     NOTE: Implementation MUST validate the X-Twilio-Signature header and
         *     return 403 for invalid signatures to prevent spoofed requests.
         */
        post: operations["handleTwilioVoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/routing/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Internal routing decision
         * @description Given campaign/supplier/call metadata, returns the selected buyer endpoint and related routing details. Internal use only.
         */
        post: operations["decideRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List suppliers */
        get: operations["listSuppliers"];
        put?: never;
        /** Create supplier */
        post: operations["createSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supplier by ID */
        get: operations["getSupplier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update supplier */
        patch: operations["updateSupplier"];
        trace?: never;
    };
    "/api/buyers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List buyers */
        get: operations["listBuyers"];
        put?: never;
        /** Create buyer */
        post: operations["createBuyer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buyers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get buyer */
        get: operations["getBuyer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update buyer */
        patch: operations["updateBuyer"];
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List campaigns */
        get: operations["listCampaigns"];
        put?: never;
        /** Create campaign */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign */
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update campaign */
        patch: operations["updateCampaign"];
        trace?: never;
    };
    "/api/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List offers */
        get: operations["listOffers"];
        put?: never;
        /** Create offer */
        post: operations["createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get offer */
        get: operations["getOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update offer */
        patch: operations["updateOffer"];
        trace?: never;
    };
    "/api/numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List phone numbers */
        get: operations["listPhoneNumbers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/numbers/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purchase and assign phone numbers from Twilio */
        post: operations["purchasePhoneNumbers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List call sessions */
        get: operations["listCallSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get call session */
        get: operations["getCallSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record conversion event (buyer → DCX) */
        post: operations["createConversionEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthCheck: {
            /** @example ok */
            status?: string;
            uptime_seconds?: number;
        };
        PaginationMeta: {
            total: number;
            page: number;
            limit: number;
        };
        PaginatedSuppliers: {
            data: components["schemas"]["Supplier"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedBuyers: {
            data: components["schemas"]["Buyer"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedCampaigns: {
            data: components["schemas"]["Campaign"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedOffers: {
            data: components["schemas"]["Offer"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedPhoneNumbers: {
            data: components["schemas"]["PhoneNumber"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedCallSessions: {
            data: components["schemas"]["CallSession"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description Subset of Twilio Voice webhook params used by DCX. Additional parameters may be present and MUST be ignored, not rejected. */
        TwilioVoiceWebhookRequest: {
            CallSid: string;
            /** @description Caller phone number (E.164) */
            From: string;
            /** @description Called (destination) number (E.164) */
            To: string;
            /** @description Twilio call status */
            CallStatus: string;
            Direction?: string;
            ApiVersion?: string;
        } & {
            [key: string]: unknown;
        };
        Supplier: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "INTERNAL_CALL_CENTER" | "EXTERNAL_PUBLISHER" | "NETWORK";
            /** Format: email */
            contact_email?: string | null;
            contact_phone?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SupplierInput: {
            name: string;
            /** @enum {string} */
            type: "INTERNAL_CALL_CENTER" | "EXTERNAL_PUBLISHER" | "NETWORK";
            /** Format: email */
            contact_email?: string | null;
            contact_phone?: string | null;
        };
        SupplierUpdate: {
            name?: string;
            /** @enum {string} */
            type?: "INTERNAL_CALL_CENTER" | "EXTERNAL_PUBLISHER" | "NETWORK";
            /** Format: email */
            contact_email?: string | null;
            contact_phone?: string | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
        };
        Buyer: {
            id: string;
            name: string;
            /** @enum {string} */
            endpoint_type: "PHONE_NUMBER" | "SIP";
            endpoint_value: string;
            concurrency_limit: number;
            daily_cap?: number | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            weight: number;
            schedule_timezone?: string | null;
            /** @description JSON object with hours-of-operation rules */
            schedule_rules?: unknown;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BuyerInput: {
            name: string;
            /** @enum {string} */
            endpoint_type: "PHONE_NUMBER" | "SIP";
            endpoint_value: string;
            concurrency_limit: number;
            daily_cap?: number | null;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** @default 50 */
            weight: number;
            schedule_timezone?: string | null;
            /** @description JSON object with hours-of-operation rules */
            schedule_rules?: unknown;
        };
        BuyerUpdate: {
            name?: string;
            /** @enum {string} */
            endpoint_type?: "PHONE_NUMBER" | "SIP";
            endpoint_value?: string;
            concurrency_limit?: number;
            daily_cap?: number | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            weight?: number;
            schedule_timezone?: string | null;
            schedule_rules?: unknown;
        };
        Campaign: {
            id: string;
            name: string;
            vertical: string;
            /** @description JSON object of allowed regions/states */
            geo_rules?: unknown;
            supplier_id?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            recording_default_enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CampaignInput: {
            name: string;
            vertical: string;
            geo_rules?: unknown;
            supplier_id?: string | null;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** @default true */
            recording_default_enabled: boolean;
        };
        CampaignUpdate: {
            name?: string;
            vertical?: string;
            geo_rules?: unknown;
            supplier_id?: string | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            recording_default_enabled?: boolean;
        };
        Offer: {
            id: string;
            buyer_id: string;
            campaign_id: string;
            /** @enum {string} */
            pricing_model: "CPA" | "FIXED" | "CPC" | "REVSHARE";
            payout_cents: number;
            buffer_seconds: number;
            attribution_window_days: number;
            daily_cap?: number | null;
            priority: number;
            weight: number;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OfferInput: {
            buyer_id: string;
            campaign_id: string;
            /** @enum {string} */
            pricing_model: "CPA" | "FIXED" | "CPC" | "REVSHARE";
            payout_cents: number;
            /** @default 60 */
            buffer_seconds: number;
            /** @default 30 */
            attribution_window_days: number;
            daily_cap?: number | null;
            /** @default 100 */
            priority: number;
            /** @default 50 */
            weight: number;
            /** @default true */
            is_active: boolean;
        };
        OfferUpdate: {
            /** @enum {string} */
            pricing_model?: "CPA" | "FIXED" | "CPC" | "REVSHARE";
            payout_cents?: number;
            buffer_seconds?: number;
            attribution_window_days?: number;
            daily_cap?: number | null;
            priority?: number;
            weight?: number;
            is_active?: boolean;
        };
        PhoneNumber: {
            id: string;
            twilio_sid: string;
            e164: string;
            campaign_id: string;
            supplier_id: string;
            /** @enum {string} */
            pool_type: "STATIC" | "DYNAMIC";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            trust_profile_id?: string | null;
            /** @enum {string|null} */
            stir_shaken_attestation?: "A" | "B" | "C" | "UNKNOWN" | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NumberPurchaseRequest: {
            /** @example US */
            country: string;
            /** @example 305 */
            area_code?: string;
            quantity: number;
            campaign_id: string;
            supplier_id: string;
            /** @enum {string} */
            pool_type: "STATIC" | "DYNAMIC";
        };
        CallSession: {
            id: string;
            public_id: string;
            trace_id: string;
            twilio_call_sid: string;
            from_number: string;
            to_number: string;
            campaign_id: string;
            supplier_id: string;
            buyer_id?: string | null;
            offer_id?: string | null;
            /** @enum {string} */
            status: "INITIATED" | "RINGING" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "BUSY" | "NO_ANSWER";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            answered_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            duration_seconds: number;
            billable_duration_seconds: number;
            telephony_cost_cents: number;
            revenue_estimated_cents: number;
            recording_enabled: boolean;
            recording_url?: string | null;
            /** @enum {string|null} */
            recording_consent_source?: "IMPLICIT_IVR" | "AGENT_VERBAL" | "NONE" | null;
            /** @enum {string} */
            transcription_status: "NONE" | "PENDING" | "COMPLETED" | "FAILED";
            transcription_text?: string | null;
            sentiment_score?: number | null;
            llm_qa_score?: number | null;
            /** Format: date-time */
            updated_at: string;
        };
        ConversionEventCreateRequest: {
            call_public_id: string;
            buyer_id: string;
            /** @example CASE_FILED */
            event_type: string;
            /** Format: date-time */
            event_time: string;
            revenue_cents?: number | null;
        };
        ConversionEventCreateResponse: {
            id: string;
            call_session_id: string;
            /** @enum {string} */
            status: "ACCEPTED";
        };
        RoutingDecisionRequest: {
            campaign_id: string;
            supplier_id: string;
            from_number: string;
            to_number: string;
            geo?: {
                country?: string;
                state?: string | null;
            } | null;
            /** Format: date-time */
            timestamp: string;
        };
        RoutingDecisionResponse: {
            buyer_id: string;
            offer_id: string;
            /** @enum {string} */
            destination_type: "PHONE_NUMBER" | "SIP";
            destination_value: string;
            max_ring_seconds: number;
            max_call_duration_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    handleTwilioVoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TwilioVoiceWebhookRequest"];
            };
        };
        responses: {
            /** @description TwiML response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/xml": string;
                };
            };
            /** @description Invalid request or missing required params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid Twilio signature (failed X-Twilio-Signature validation) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    decideRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful routing decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingDecisionResponse"];
                };
            };
            /** @description Invalid routing input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No eligible buyer routes found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSuppliers: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "INACTIVE";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of suppliers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSuppliers"];
                };
            };
        };
    };
    createSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierInput"];
            };
        };
        responses: {
            /** @description Supplier created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    getSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supplier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
            /** @description Supplier not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Updated supplier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
            /** @description Supplier not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listBuyers: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "INACTIVE";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of buyers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBuyers"];
                };
            };
        };
    };
    createBuyer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerInput"];
            };
        };
        responses: {
            /** @description Buyer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Buyer"];
                };
            };
        };
    };
    getBuyer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Buyer"];
                };
            };
            /** @description Buyer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBuyer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerUpdate"];
            };
        };
        responses: {
            /** @description Updated buyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Buyer"];
                };
            };
            /** @description Buyer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCampaigns: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "INACTIVE";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of campaigns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCampaigns"];
                };
            };
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignInput"];
            };
        };
        responses: {
            /** @description Campaign created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignUpdate"];
            };
        };
        responses: {
            /** @description Updated campaign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOffers: {
        parameters: {
            query?: {
                campaign_id?: string;
                buyer_id?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of offers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOffers"];
                };
            };
        };
    };
    createOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferInput"];
            };
        };
        responses: {
            /** @description Offer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
        };
    };
    getOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            /** @description Offer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferUpdate"];
            };
        };
        responses: {
            /** @description Updated offer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            /** @description Offer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPhoneNumbers: {
        parameters: {
            query?: {
                campaign_id?: string;
                supplier_id?: string;
                status?: "ACTIVE" | "INACTIVE";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of phone numbers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPhoneNumbers"];
                };
            };
        };
    };
    purchasePhoneNumbers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NumberPurchaseRequest"];
            };
        };
        responses: {
            /** @description Phone numbers purchased */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"][];
                };
            };
        };
    };
    listCallSessions: {
        parameters: {
            query?: {
                /** @description Start of date range (ISO 8601) */
                from?: string;
                /** @description End of date range (ISO 8601) */
                to?: string;
                campaign_id?: string;
                supplier_id?: string;
                buyer_id?: string;
                status?: "INITIATED" | "RINGING" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "BUSY" | "NO_ANSWER";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of call sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCallSessions"];
                };
            };
        };
    };
    getCallSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Call session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallSession"];
                };
            };
            /** @description Call session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createConversionEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversionEventCreateRequest"];
            };
        };
        responses: {
            /** @description Conversion event recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionEventCreateResponse"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Call not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
